title:       NeurIPS 2026 Workshop on Neural Network Artifacts as a New Data Modality
url:         "https://artifactsasdata.org"
baseurl:     ""
# description:
# timezone: France/Pari

navigation:
  Home: "/"
  Call for Papers: "/cfp"
  Schedule: "/schedule"
  Speakers: "/speakers"
  Organizers: "/organizers"
  # Programme Committee: "/committee"
  # FAQ: "/faq"

markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
